#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER_DSS WITH PASSWORD '$POSTGRES_PASSWORD_DSS';
    CREATE DATABASE $POSTGRES_DATABASE_DSS;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DATABASE_DSS TO $POSTGRES_USER_DSS;
EOSQL
